name: Docker Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t hbm1g18/appendix .

    - name: Push Docker image to Docker Hub
      run: docker push hbm1g18/appendix

    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull hbm1g18/appendix
          docker stop appendix-gen || true
          docker rm appendix-gen || true
          docker run -d --name appendix-gen -p 8080:8080 -e FLASK_RUN_HOST=0.0.0.0 hbm1g18/appendix
