name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{ secrets.EC2_HOST }}
            USER_NAME: ${{ secrets.EC2_USERNAME }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              # Change directory to your app directory
              cd /path/to/your/app/gwp_appendix_flask &&
              
              # Update the code from the main branch
              git pull origin main &&
              
              # Stop the Docker container if it's running
              docker stop appendix || true &&
              
              # Build the Docker image
              docker build -t appendix . &&
              
              # Run the Docker container
              docker run -d -p 8080:8080 -e FLASK_RUN_HOST=0.0.0.0 appendix
              '

